#!/bin/bash

# Braxis Campaign Script - Generate, commit, and show PR description
# Usage: ./braxis_campaign_with_pr_mac.sh owner/repo [github-username]
# This version shows the auto-generated PR description for guidance

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Parse arguments
if [[ -z "$1" ]]; then
  echo -e "${RED}Usage: $0 owner/repo [github-username]${NC}"
  echo "Example: $0 elastic/kibana jaykrishna316"
  exit 1
fi

REPO="$1"
GITHUB_USER="${2:-jaykrishna316}"
IFS='/' read -r OWNER REPO_NAME <<< "$REPO"

# Configuration
CAMPAIGN_DIR="${HOME}/braxis_campaign"
REPO_DIR="${CAMPAIGN_DIR}/${REPO_NAME}"
BRAXIS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Find python
if command -v python3 &> /dev/null; then
  PYTHON_CMD="python3"
else
  PYTHON_CMD="python"
fi

# Create campaign directory
mkdir -p "${CAMPAIGN_DIR}"

echo -e "${BLUE}=== Braxis Campaign: ${REPO} ===${NC}"
echo "Campaign directory: ${CAMPAIGN_DIR}"
echo ""

# Clone if not exists
if [ ! -d "${REPO_DIR}" ]; then
  echo -e "${YELLOW}Cloning ${REPO}...${NC}"
  git clone "https://github.com/${REPO}.git" "${REPO_DIR}" || {
    echo -e "${RED}✗ Failed to clone ${REPO}${NC}"
    exit 1
  }
else
  echo -e "${YELLOW}Repository already cloned, pulling latest...${NC}"
  cd "${REPO_DIR}"
  git pull origin main 2>/dev/null || git pull origin master 2>/dev/null || git pull origin devel 2>/dev/null || true
  cd "${CAMPAIGN_DIR}"
fi

cd "${REPO_DIR}"

# Check if AGENTS.md already exists
if [ -f "AGENTS.md" ]; then
  echo -e "${YELLOW}⚠ AGENTS.md already exists - will create updated version${NC}"
fi

# Generate AGENTS.md using braxis
echo -e "${YELLOW}Generating AGENTS.md with braxis...${NC}"
if ${PYTHON_CMD} "${BRAXIS_PATH}/braxis.py" generate --path . >/dev/null 2>&1; then

  if [ ! -f "AGENTS.md" ]; then
    echo -e "${RED}✗ AGENTS.md generation failed${NC}"
    exit 1
  fi

  # Get current branch
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  # Create feature branch
  FEATURE_BRANCH="braxis/add-agents-md-$(date +%s)"
  git checkout -b "${FEATURE_BRANCH}" 2>/dev/null || git checkout -b "${FEATURE_BRANCH}"

  # Commit AGENTS.md
  echo -e "${YELLOW}Committing AGENTS.md...${NC}"
  git add AGENTS.md CLAUDE.md .cursorrules .agentic-config.json
  git commit -m "feat: Add/update AGENTS.md for AI agent guidance

Generated by Braxis
https://github.com/${GITHUB_USER}/braxis

Co-Authored-By: Jayakrishna Ichapurapu <jaykrishna316@gmail.com>" 2>/dev/null

  # Try push to origin (will fail if no write access)
  echo -e "${YELLOW}Attempting push to origin...${NC}"
  if git push -u origin "${FEATURE_BRANCH}" 2>/dev/null; then
    # Direct push worked
    echo -e "${GREEN}✓ Successfully pushed to ${REPO}${NC}"
    echo ""
    echo -e "${BLUE}Create PR at:${NC}"
    echo "https://github.com/${REPO}/compare/main...${FEATURE_BRANCH}?expand=1"

    # Show PR description guidance
    echo ""
    echo -e "${CYAN}=== SUGGESTED PR DESCRIPTION ===${NC}"
    echo ""
    ${PYTHON_CMD} "${BRAXIS_PATH}/campaign_pr_generator.py" "${REPO_DIR}"

  else
    # No write access - need fork workflow
    echo -e "${YELLOW}⚠ No direct access. Using fork workflow...${NC}"
    echo ""
    echo -e "${BLUE}STEP 1: Fork the repo${NC}"
    echo "Go to: https://github.com/${OWNER}/${REPO_NAME}"
    echo "Click the Fork button (top right)"
    echo ""
    echo -e "${BLUE}STEP 2: Wait for fork to complete, then run:${NC}"
    echo "git remote set-url origin https://github.com/${GITHUB_USER}/${REPO_NAME}.git"
    echo "git push -u origin ${FEATURE_BRANCH}"
    echo ""
    echo -e "${BLUE}STEP 3: Create PR:${NC}"
    echo "https://github.com/${OWNER}/${REPO_NAME}/compare/main...${GITHUB_USER}:${FEATURE_BRANCH}?expand=1"
    echo ""
    echo -e "${CYAN}STEP 4: Use this PR description:${NC}"
    echo ""
    ${PYTHON_CMD} "${BRAXIS_PATH}/campaign_pr_generator.py" "${REPO_DIR}"
    echo ""
    echo -e "${YELLOW}Branch ready at: ${REPO_DIR}${NC}"
    exit 1
  fi
else
  echo -e "${RED}✗ AGENTS.md generation failed${NC}"
  exit 1
fi

cd "${CAMPAIGN_DIR}"
echo -e "${GREEN}✓ Campaign complete for ${REPO}${NC}"
