#!/usr/bin/env python3
import sys, json, argparse
from pathlib import Path

def generate():
    with open('AGENTS.md', 'w') as f:
        f.write("# AGENTS.md\nGenerated by Braxis")
    with open('CLAUDE.md', 'w') as f:
        f.write("# CLAUDE.md\nGenerated by Braxis")
    with open('.cursorrules', 'w') as f:
        f.write("# Cursor Rules\nGenerated by Braxis")
    with open('.agentic-config.json', 'w') as f:
        f.write('{"name": "Project"}')
    print("✅ Generated: AGENTS.md, CLAUDE.md, .cursorrules, .agentic-config.json")

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'generate':
        generate()
    elif len(sys.argv) > 1 and sys.argv[1] == '--help':
        print("braxis generate - Generate context files")
    else:
        print("braxis v1.0.0\nUsage: braxis generate")
