#!/bin/bash

# Braxis Campaign Script - Generate and push AGENTS.md to a single repo
# Usage: ./braxis_campaign_mac.sh owner/repo
# Example: ./braxis_campaign_mac.sh elastic/kibana

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
if [[ -z "$1" ]]; then
  echo -e "${RED}Usage: $0 owner/repo${NC}"
  echo "Example: $0 elastic/kibana"
  exit 1
fi

REPO="$1"
IFS='/' read -r OWNER REPO_NAME <<< "$REPO"

# Configuration
CAMPAIGN_DIR="${HOME}/braxis_campaign"
BRAXIS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${CAMPAIGN_DIR}/${REPO_NAME}"

# Create campaign directory
mkdir -p "${CAMPAIGN_DIR}"

echo -e "${BLUE}=== Braxis Campaign: ${REPO} ===${NC}"
echo "Campaign directory: ${CAMPAIGN_DIR}"
echo ""

# Clone if not exists
if [ ! -d "${REPO_DIR}" ]; then
  echo -e "${YELLOW}Cloning ${REPO}...${NC}"
  git clone "https://github.com/${REPO}.git" "${REPO_DIR}" || {
    echo -e "${RED}✗ Failed to clone ${REPO}${NC}"
    exit 1
  }
else
  echo -e "${YELLOW}Repository already cloned, pulling latest...${NC}"
  cd "${REPO_DIR}"
  git pull origin main 2>/dev/null || git pull origin master 2>/dev/null || true
  cd "${CAMPAIGN_DIR}"
fi

cd "${REPO_DIR}"

# Check if AGENTS.md already exists
if [ -f "AGENTS.md" ]; then
  echo -e "${YELLOW}⚠ AGENTS.md already exists in ${REPO}${NC}"
  echo "Skipping generation."
  cd "${CAMPAIGN_DIR}"
  exit 0
fi

# Generate AGENTS.md using braxis
echo -e "${YELLOW}Generating AGENTS.md with braxis...${NC}"
if python "${BRAXIS_PATH}/braxis.py" generate --output-file AGENTS.md . >/dev/null 2>&1; then

  if [ ! -f "AGENTS.md" ]; then
    echo -e "${RED}✗ AGENTS.md generation failed${NC}"
    exit 1
  fi

  # Get current branch
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  # Create feature branch
  FEATURE_BRANCH="braxis/add-agents-md-$(date +%s)"
  git checkout -b "${FEATURE_BRANCH}" 2>/dev/null || git checkout -b "${FEATURE_BRANCH}"

  # Commit AGENTS.md
  echo -e "${YELLOW}Committing AGENTS.md...${NC}"
  git add AGENTS.md
  git commit -m "feat: Add AGENTS.md for AI agent guidance

This file provides comprehensive guidance for AI agents working on this project.

Category A: Operations Manual (extracted from CONTRIBUTING.md)
- AI policies and constraints
- Development procedures
- Build and test requirements

Category B: Context Guide (auto-generated)
- Architecture overview
- Project structure
- Development workflow
- Code conventions and testing strategy

Generated by Braxis - keeping AI agents in sync with your code
https://github.com/anthropics/braxis

Co-Authored-By: Claude Haiku 4.5 <noreply@anthropic.com>" 2>/dev/null

  # Push to origin
  echo -e "${YELLOW}Pushing branch ${FEATURE_BRANCH}...${NC}"
  if git push -u origin "${FEATURE_BRANCH}" 2>/dev/null; then
    echo -e "${GREEN}✓ Successfully pushed to ${REPO}${NC}"
    echo ""
    echo -e "${BLUE}Create PR at:${NC}"
    echo "https://github.com/${REPO}/compare/main...${FEATURE_BRANCH}?expand=1"
    echo ""
  else
    echo -e "${RED}✗ Push failed (likely no write access)${NC}"
    echo "You may need to fork the repository first and push to your fork."
    exit 1
  fi
else
  echo -e "${RED}✗ AGENTS.md generation failed${NC}"
  exit 1
fi

cd "${CAMPAIGN_DIR}"
echo -e "${GREEN}✓ Campaign complete for ${REPO}${NC}"
