#!/bin/bash

# Braxis Campaign Script - Generate and push AGENTS.md to multiple repos
# Usage: ./braxis_campaign.sh [repo1] [repo2] ... or ./braxis_campaign.sh --all

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
CAMPAIGN_DIR="${HOME}/braxis_campaign"
BRAXIS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Repos to process
REPOS=(
  "elastic/kibana"
  "getsentry/sentry"
  "datadog/dd-trace-py"
  "newrelic/newrelic-python-agent"
  "jaegertracing/jaeger"
  "open-telemetry/opentelemetry-python"
  "influxdata/telegraf"
  "alibaba/sentinel"
)

# Parse arguments
if [[ "$1" == "--all" ]]; then
  SELECTED_REPOS=("${REPOS[@]}")
elif [[ -z "$1" ]]; then
  echo -e "${RED}Usage: $0 [--all|repo1 repo2 ...]${NC}"
  echo "Example: $0 --all"
  echo "Example: $0 elastic/kibana getsentry/sentry"
  exit 1
else
  SELECTED_REPOS=("$@")
fi

# Create campaign directory
mkdir -p "${CAMPAIGN_DIR}"
cd "${CAMPAIGN_DIR}"

echo -e "${BLUE}=== Braxis Campaign: Generating AGENTS.md ===${NC}"
echo "Campaign directory: ${CAMPAIGN_DIR}"
echo "Processing ${#SELECTED_REPOS[@]} repos..."
echo ""

SUMMARY_FILE="${CAMPAIGN_DIR}/campaign_summary.txt"
> "${SUMMARY_FILE}"

# Process each repo
for REPO in "${SELECTED_REPOS[@]}"; do
  IFS='/' read -r OWNER REPO_NAME <<< "$REPO"

  echo -e "${YELLOW}Processing: ${REPO}${NC}"

  REPO_DIR="${CAMPAIGN_DIR}/${REPO_NAME}"

  # Clone if not exists
  if [ ! -d "${REPO_DIR}" ]; then
    echo "  Cloning ${REPO}..."
    git clone "https://github.com/${REPO}.git" "${REPO_DIR}" 2>/dev/null || {
      echo -e "${RED}  ✗ Failed to clone ${REPO}${NC}"
      echo "FAILED: ${REPO} - Clone failed" >> "${SUMMARY_FILE}"
      continue
    }
  else
    echo "  Repository already cloned, pulling latest..."
    cd "${REPO_DIR}"
    git pull origin main 2>/dev/null || git pull origin master 2>/dev/null || true
    cd "${CAMPAIGN_DIR}"
  fi

  cd "${REPO_DIR}"

  # Check if AGENTS.md already exists
  if [ -f "AGENTS.md" ]; then
    echo -e "${YELLOW}  ⚠ AGENTS.md already exists - will create updated version${NC}"
  fi

  # Generate AGENTS.md using braxis
  echo "  Generating AGENTS.md with braxis..."
  if python "${BRAXIS_PATH}/braxis.py" generate --output-file AGENTS.md . >/dev/null 2>&1; then

    if [ ! -f "AGENTS.md" ]; then
      echo -e "${RED}  ✗ AGENTS.md generation failed${NC}"
      echo "FAILED: ${REPO} - Generation produced no file" >> "${SUMMARY_FILE}"
      cd "${CAMPAIGN_DIR}"
      continue
    fi

    # Get current branch
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

    # Create feature branch
    FEATURE_BRANCH="braxis/add-agents-md-$(date +%s)"
    git checkout -b "${FEATURE_BRANCH}" 2>/dev/null || git checkout -b "${FEATURE_BRANCH}"

    # Commit AGENTS.md
    git add AGENTS.md
    git commit -m "feat: Add/update AGENTS.md for AI agent guidance

This file provides comprehensive guidance for AI agents working on this project.

Dual-Format Structure:

Category A: Operations Manual (extracted from CONTRIBUTING.md)
- AI policies and constraints
- Development procedures
- Build and test requirements
- Known workarounds

Category B: Context Guide (auto-generated)
- Architecture overview
- Project structure
- Development workflow
- Code conventions and testing strategy
- AI readiness scoring

Generated by Braxis - keeping AI agents in sync with your code
https://github.com/anthropics/braxis

For maintainers: This is a suggested enhancement to your agent guidance.
Please review and adjust as needed for your project.

Co-Authored-By: Claude Haiku 4.5 <noreply@anthropic.com>" 2>/dev/null

    # Push to origin
    echo "  Pushing branch ${FEATURE_BRANCH}..."
    if git push -u origin "${FEATURE_BRANCH}" 2>/dev/null; then
      echo -e "${GREEN}  ✓ Successfully pushed to ${REPO}${NC}"
      echo "SUCCESS: ${REPO} - Branch pushed to ${FEATURE_BRANCH}" >> "${SUMMARY_FILE}"
      echo "  PR URL: https://github.com/${REPO}/compare/main...${FEATURE_BRANCH}?expand=1"
    else
      echo -e "${RED}  ✗ Push failed (likely no write access)${NC}"
      echo "PUSH_FAILED: ${REPO} - No write access to origin" >> "${SUMMARY_FILE}"
    fi
  else
    echo -e "${RED}  ✗ AGENTS.md generation failed${NC}"
    echo "FAILED: ${REPO} - Generation command failed" >> "${SUMMARY_FILE}"
  fi

  cd "${CAMPAIGN_DIR}"
  echo ""
done

# Print summary
echo -e "${BLUE}=== Campaign Summary ===${NC}"
cat "${SUMMARY_FILE}"
echo ""
echo -e "${BLUE}Campaign directory: ${CAMPAIGN_DIR}${NC}"
echo -e "${GREEN}✓ Campaign complete${NC}"
