#!/usr/bin/env python3
"""
Campaign PR Generator - Auto-generate PR descriptions with Braxis messaging
"""
import sys
from pathlib import Path
from braxis import BraxisAnalyzer

def generate_campaign_pr(repo_path):
    """Generate a PR description for a campaign repo."""
    try:
        analyzer = BraxisAnalyzer(repo_path)
        analyzer.analyze()

        pr_description = analyzer.generate_pr_description()

        # Print in sections
        print(f"\n{'='*80}")
        print(f"PR DESCRIPTION FOR: {analyzer.project_path.name}")
        print(f"AI Readiness: {analyzer.total_score}/100 ({analyzer.tier})")
        print(f"{'='*80}\n")

        print(pr_description)

        print(f"\n{'='*80}")
        print("BRANCH NAME SUGGESTION:")
        print(f"braxis/add-agents-md-$(date +%s)")
        print(f"\nCOMMIT MESSAGE:")
        print("""feat: Add/update AGENTS.md for AI agent guidance

Generated by Braxis
https://github.com/jaykrishna316/braxis

Co-Authored-By: Jayakrishna Ichapurapu <jaykrishna316@gmail.com>""")
        print(f"{'='*80}\n")

        # Check for existing AGENTS.md
        existing = analyzer.detect_existing_agents_md()
        if existing:
            print(f"✓ Existing AGENTS.md detected (Quality: {existing['score']}/100)")
            if existing['score'] >= 50:
                print("  → Recommend: Keep existing + accept other 3 files (Option B)")
            else:
                print("  → Recommend: Replace or merge (Options A/C)")
        else:
            print("✓ No existing AGENTS.md (Recommend: Accept all files)")

        return pr_description

    except Exception as e:
        print(f"Error analyzing {repo_path}: {e}", file=sys.stderr)
        return None

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python3 campaign_pr_generator.py <repo_path>")
        print("Example: python3 campaign_pr_generator.py ~/braxis_campaign/meteor")
        sys.exit(1)

    repo_path = sys.argv[1]
    generate_campaign_pr(repo_path)
