#!/bin/bash

# Braxis Tier 10 Campaign - Full Workflow with PR Generation
# Generates AGENTS.md, creates branch, commits, and shows PR descriptions
# Usage: ./tier10_campaign.sh [repo_number]
# repo_number: 1-7 for individual repos, or omit for interactive menu

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
CAMPAIGN_DIR="${HOME}/braxis_campaign"
BRAXIS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GITHUB_USER="jaykrishna316"

# Tier 10 Repositories (7 successfully analyzed)
declare -a TIER10_REPOS=(
  "ninja-build/ninja:Ninja Build System:C++"
  "bazelbuild/bazel:Bazel (Google Build):Java"
  "facebook/buck2:Buck2 (Meta Build):Rust"
  "mesonbuild/meson:Meson Build System:C"
  "scons/scons:SCons Python Build:Python"
  "pantsbuild/pants:Pants Build Framework:Python"
  "waf-project/waf:WAF Build System:Python"
)

# Find python
if command -v python3 &> /dev/null; then
  PYTHON_CMD="python3"
else
  PYTHON_CMD="python"
fi

# Print menu
print_menu() {
  echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BLUE}║         Braxis Tier 10 Campaign - Build Systems (7/10)         ║${NC}"
  echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
  echo ""

  local i=1
  for repo_info in "${TIER10_REPOS[@]}"; do
    IFS=':' read -r repo_url repo_title repo_lang <<< "$repo_info"
    printf "  ${CYAN}%d)${NC} %-40s ${YELLOW}(%s)${NC}\n" "$i" "$repo_title" "$repo_lang"
    ((i++))
  done

  echo ""
  echo -e "${CYAN}0${NC} - Exit"
  echo ""
}

# Process single repository
process_repo() {
  local repo_info="$1"
  local repo_index="$2"

  IFS=':' read -r REPO REPO_TITLE REPO_LANG <<< "$repo_info"
  IFS='/' read -r OWNER REPO_NAME <<< "$REPO"

  REPO_DIR="${CAMPAIGN_DIR}/${REPO_NAME}"

  echo ""
  echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}Repository ${repo_index}: ${REPO_TITLE}${NC}"
  echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
  echo ""

  # Clone if not exists
  mkdir -p "${CAMPAIGN_DIR}"

  if [ ! -d "${REPO_DIR}" ]; then
    echo -e "${YELLOW}[1/6] Cloning ${REPO}...${NC}"
    git clone --depth 1 "https://github.com/${REPO}.git" "${REPO_DIR}" 2>&1 | grep -E "^Cloning|fatal" || true

    if [ ! -d "${REPO_DIR}/.git" ]; then
      echo -e "${RED}✗ Clone failed for ${REPO}${NC}"
      return 1
    fi
  else
    echo -e "${YELLOW}[1/6] Repository already cloned${NC}"
    cd "${REPO_DIR}"
    git fetch origin 2>/dev/null || true
    cd "${CAMPAIGN_DIR}"
  fi

  cd "${REPO_DIR}"

  # Check existing AGENTS.md
  if [ -f "AGENTS.md" ]; then
    echo -e "${YELLOW}[2/6] AGENTS.md already exists - generating updated version${NC}"
  else
    echo -e "${YELLOW}[2/6] No AGENTS.md found - generating new version${NC}"
  fi

  # Generate with braxis
  echo -e "${YELLOW}[3/6] Running braxis generate...${NC}"
  if ! ${PYTHON_CMD} "${BRAXIS_PATH}/braxis.py" generate --path . > /tmp/braxis_gen_${REPO_NAME}.log 2>&1; then
    echo -e "${RED}✗ Braxis generation failed${NC}"
    cat /tmp/braxis_gen_${REPO_NAME}.log | tail -5
    return 1
  fi

  # Extract score for display
  SCORE=$(grep "Agent Readiness:" /tmp/braxis_gen_${REPO_NAME}.log | sed 's/.*: //' | cut -d'/' -f1)
  echo -e "${GREEN}✓ Generated successfully (Score: ${SCORE}/100)${NC}"

  # Create branch
  FEATURE_BRANCH="braxis/add-agents-md-$(date +%s)"
  echo -e "${YELLOW}[4/6] Creating branch: ${FEATURE_BRANCH}${NC}"
  git checkout -b "${FEATURE_BRANCH}" 2>/dev/null || true

  # Commit
  echo -e "${YELLOW}[5/6] Committing files...${NC}"
  git add AGENTS.md CLAUDE.md .cursorrules .agentic-config.json 2>/dev/null || true

  if ! git commit -m "feat: Add/update AGENTS.md for AI agent guidance

Generated by Braxis
https://github.com/${GITHUB_USER}/braxis

Co-Authored-By: Jayakrishna Ichapurapu <jaykrishna316@gmail.com>" 2>/dev/null; then
    echo -e "${YELLOW}✓ No changes needed (files already committed)${NC}"
  else
    echo -e "${GREEN}✓ Committed${NC}"
  fi

  # Generate PR description
  echo -e "${YELLOW}[6/6] Generating PR description...${NC}"
  echo ""

  ${PYTHON_CMD} "${BRAXIS_PATH}/campaign_pr_generator.py" "${REPO_DIR}" 2>/dev/null

  echo ""
  echo -e "${GREEN}Ready to push to fork:${NC}"
  echo "  Branch: ${FEATURE_BRANCH}"
  echo "  URL: https://github.com/${GITHUB_USER}/${REPO_NAME}"
  echo ""
  echo -e "${CYAN}To push, run:${NC}"
  echo "  cd ${REPO_DIR}"
  echo "  git remote set-url origin https://github.com/${GITHUB_USER}/${REPO_NAME}.git"
  echo "  git push -u origin ${FEATURE_BRANCH}"
  echo ""

  read -p "Push now? (y/n): " -n 1 -r
  echo ""

  if [[ $REPLY =~ ^[Yy]$ ]]; then
    git remote set-url origin "https://github.com/${GITHUB_USER}/${REPO_NAME}.git"
    if git push -u origin "${FEATURE_BRANCH}" 2>&1 | tail -3; then
      echo -e "${GREEN}✓ Pushed successfully${NC}"
      echo ""
      echo -e "${GREEN}Create PR at: https://github.com/${OWNER}/${REPO_NAME}/compare/main...${GITHUB_USER}:${REPO_NAME}:${FEATURE_BRANCH}${NC}"
    else
      echo -e "${RED}✗ Push failed${NC}"
    fi
  else
    echo -e "${CYAN}Skipped push. Ready when you are.${NC}"
  fi

  cd "${CAMPAIGN_DIR}"
  echo ""
}

# Main
if [[ -z "$1" ]]; then
  # Interactive menu
  while true; do
    print_menu
    read -p "Select repository (0-7): " choice

    if [ "$choice" == "0" ]; then
      echo -e "${GREEN}Exiting...${NC}"
      exit 0
    fi

    if [ "$choice" -ge 1 ] && [ "$choice" -le 7 ]; then
      # Get repo at index (choice-1)
      repo_info="${TIER10_REPOS[$((choice-1))]}"
      process_repo "$repo_info" "$choice"

      echo ""
      read -p "Press Enter to continue..."
    else
      echo -e "${RED}Invalid selection${NC}"
    fi
  done
else
  # Process specific repo
  if [ "$1" -ge 1 ] && [ "$1" -le 7 ]; then
    repo_info="${TIER10_REPOS[$((1-1))]}"
    process_repo "$repo_info" "$1"
  else
    echo "Usage: $0 [1-7]"
    echo "  1 = Ninja"
    echo "  2 = Bazel"
    echo "  3 = Buck2"
    echo "  4 = Meson"
    echo "  5 = SCons"
    echo "  6 = Pants"
    echo "  7 = WAF"
  fi
fi
