#!/bin/bash
# Braxis Tier 10 Campaign - Condensed PR with auto-create
# Usage: bash tier10_campaign_condensed.sh <owner/repo> [github-username]
# Example: bash tier10_campaign_condensed.sh ninja-build/ninja jaykrishna316

REPO="${1:-pantsbuild/pants}"
GITHUB_USER="${2:-jaykrishna316}"
IFS='/' read -r REPO_OWNER REPO_NAME <<< "$REPO"

CAMPAIGN_DIR="$HOME/braxis_campaign"
REPO_DIR="$CAMPAIGN_DIR/$REPO_NAME"
BRAXIS_PATH="/Users/binarymind/Desktop/braxis"

# Create campaign directory
mkdir -p "$CAMPAIGN_DIR"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Braxis Campaign: $REPO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Clone or pull
if [ ! -d "$REPO_DIR" ]; then
  echo "📦 Cloning $REPO..."
  git clone "https://github.com/$REPO.git" "$REPO_DIR" || { echo "❌ Clone failed"; exit 1; }
else
  echo "📦 Updating $REPO_NAME..."
  cd "$REPO_DIR"
  git pull origin main 2>/dev/null || git pull origin master 2>/dev/null || true
fi

cd "$REPO_DIR"

# Generate
echo "🔍 Running braxis generate..."
if ! /usr/local/bin/python3 "$BRAXIS_PATH/braxis.py" generate --path . > /tmp/braxis_gen.log 2>&1; then
  echo "❌ Braxis generation failed"
  cat /tmp/braxis_gen.log | tail -5
  exit 1
fi

SCORE=$(grep "Agent Readiness:" /tmp/braxis_gen.log | sed 's/.*: //' | cut -d'/' -f1)
echo "✅ Score: $SCORE/100"
echo ""

# Stage and commit
echo "📝 Creating commit..."
git add AGENTS.md CLAUDE.md .cursorrules .agentic-config.json
BRANCH="braxis/add-agents-md-$(date +%s)"
git checkout -b "$BRANCH"
git commit -m "feat: Add/update AGENTS.md for AI agent guidance

Generated by Braxis
https://github.com/jaykrishna316/braxis

Co-Authored-By: Jayakrishna Ichapurapu <jaykrishna316@gmail.com>"

# Set remote and push
echo "📤 Pushing to fork..."
git remote set-url origin "https://github.com/$GITHUB_USER/$REPO_NAME.git"
git push -u origin "$BRANCH"

# Create condensed PR
echo "🚀 Creating PR..."
echo ""

PR_TITLE="feat: Add/update AGENTS.md for AI agent guidance"
PR_BODY="## Braxis: AI Context Files for Your Repository

**AI Readiness Score: $SCORE/100**

We've generated 4 AI-ready context files:
- **AGENTS.md** — Agent guidance + architecture
- **CLAUDE.md** — Quick reference
- **.cursorrules** — IDE conventions
- **.agentic-config.json** — Agent config

### What This Does

✅ AI agents understand your codebase better
✅ Consistent guidance across all tools
✅ Auto-updates via GitHub Actions workflow

### Next Step: Install Auto-Updates

Add this workflow to keep files fresh on code changes:

\`\`\`yaml
# .github/workflows/ai-context.yml
name: Auto-Update AI Context

on:
  push:
    branches: [main, master, devel]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install braxis && braxis generate --smart-merge
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: auto-update AI context'
          title: 'chore: auto-update AI context'
          branch: braxis/auto-update
\`\`\`

📖 [Braxis Docs](https://github.com/jaykrishna316/braxis)"

gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --head "$GITHUB_USER:$BRANCH" \
  --base main \
  --repo "$REPO_OWNER/$REPO_NAME" 2>/dev/null

if [ $? -eq 0 ]; then
  echo "✅ PR created successfully!"
else
  echo "⚠️  gh cli not configured. Manual PR:"
fi

echo ""
echo "📋 PR URL: https://github.com/$REPO_OWNER/$REPO_NAME/compare/main...$GITHUB_USER:$BRANCH"
echo ""
